### ISSUE TITLE
Password Reset Feature

### ISSUE THREAD

**Issue by WayneLambert** [WayneLambert/portfolio#13]
The password reset feature needs to be investigated. It does not seem to recognise the address.

**Comment by WayneLambert** [comment]
For user email addresses found in the database, it returns a message saying:

```sh
web_1       | Internal Server Error: /blog/users/password-reset/
web_1       | Traceback (most recent call last):
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
web_1       |     response = get_response(request)
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
web_1       |     response = self.process_exception_by_middleware(e, request)
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
web_1       |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
web_1       |     return self.dispatch(request, *args, **kwargs)
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
web_1       |     return bound_method(*args, **kwargs)
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
web_1       |     response = view_func(request, *args, **kwargs)
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/views.py", line 222, in dispatch
web_1       |     return super().dispatch(*args, **kwargs)
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 97, in dispatch
web_1       |     return handler(request, *args, **kwargs)
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/views/generic/edit.py", line 142, in post
web_1       |     return self.form_valid(form)
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/views.py", line 235, in form_valid
web_1       |     form.save(**opts)
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/forms.py", line 322, in save
web_1       |     self.send_mail(
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/forms.py", line 272, in send_mail
web_1       |     email_message.send()
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/core/mail/message.py", line 276, in send
web_1       |     return self.get_connection(fail_silently).send_messages([self])
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 109, in send_messages
web_1       |     sent = self._send(message)
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 121, in _send
web_1       |     from_email = sanitize_address(email_message.from_email, encoding)
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/core/mail/message.py", line 88, in sanitize_address
web_1       |     raise ValueError(
web_1       | ValueError: Invalid address; only 'Wayne Lambert <wayne.a.lambert@gmail.com> could be parsed from "'Wayne Lambert <wayne.a.lambert@gmail.com>'"
web_1       | [13/Jun/2020 21:24:09] "POST /blog/users/password-reset/ HTTP/1.1" 500 151440
```

This needs to be investigated further.

**Comment by WayneLambert** [comment]
The reason why the above error message happens is because of the project's previous development settings using Gmail's SMTP mail server settings. They are improperly configured which, according to some forum suggestions, are according to changes in Gmail's protocol. This feature works on the current production site which uses Amazon's SES.

The feature also sends the password reset link to my mailbox when resetting from the development site. Clicking the link to actually test the password reset functionality does not work because the production site did not actually request the password reset.

This needs to be restested after the site goes lives, therefore leaving issue open.

**Comment by WayneLambert** [comment]
Issue resolved. I have also improved the presentation of all forms and pages within the registration, login, and forgotten password processes.
